// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "ts-node -r tsconfig-paths/register prisma/seed.ts",
  },
  datasource: {
    // La CLI (migrate/db push) a besoin d'une connexion directe : le pooler
    // Neon (PgBouncer) ne supporte pas l'advisory lock que `migrate deploy`
    // utilise, ce qui cause un timeout P1002. DATABASE_URL (pooler) reste
    // utilisée par le client applicatif dans prisma.service.ts.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
